services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tamayodb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - ENVIRONMENT=local
      # Python debugging
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      # FastAPI debugging
      - DEBUG=1
    # Ensure all logs are captured
    volumes:
      - ./backend/app:/app/app
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    # Keep container running for debugging
    tty: true
    stdin_open: true
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
