"""created table for image generations

Revision ID: 2581cbe2d8b0
Revises: 382104ab53b8
Create Date: 2025-09-25 04:07:32.514610

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2581cbe2d8b0'
down_revision = '382104ab53b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagegeneration',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['generation_id'], ['generation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('generation', 'cost',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generation', 'cost',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_table('imagegeneration')
    # ### end Alembic commands ###
