"""updated canvas tables and relationships

Revision ID: 51436b5cfd81
Revises: 65b1030d59ff
Create Date: 2025-10-02 18:19:44.435735

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51436b5cfd81'
down_revision = '65b1030d59ff'
branch_labels = None
depends_on = None
CANVAS_ID = "18c6938e-90a8-44a7-a627-7fa4688094e6"

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('imagegeneration', 'image')
    op.drop_table('canvashistory')
    op.alter_column('canvas', 'prompt', new_column_name='title')
    op.add_column('generation', sa.Column('canvas_id', sa.Uuid(), nullable=False, server_default=sa.text(f"'{CANVAS_ID}'")))
    op.create_foreign_key('fk_generation_canvas_id', 'generation', 'canvas', ['canvas_id'], ['id'], ondelete='CASCADE')
    op.drop_column('generation', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation', sa.Column('title', sa.String(), nullable=True))
    op.drop_constraint('fk_generation_canvas_id', 'generation', type_='foreignkey')
    op.drop_column('generation', 'canvas_id')
    op.alter_column('canvas', 'title', new_column_name='prompt')
    op.create_table('canvashistory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canvas_id', sa.Uuid(), nullable=False),
    sa.Column('old_prompt', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.rename_table('image', 'imagegeneration')
    # ### end Alembic commands ###
