"""added status

Revision ID: 65b1030d59ff
Revises: f443220341eb
Create Date: 2025-09-30 18:39:56.318249

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '65b1030d59ff'
down_revision = 'f443220341eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # create enum
    generation_status_enum = sa.Enum(
        'pending', 'completed', 'failed',
        name='generationstatus'
    )
    generation_status_enum.create(op.get_bind(), checkfirst=True)
    # add column to table
    op.add_column('generation', sa.Column('status', generation_status_enum, nullable=False, server_default='completed'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation', 'status')
    sa.Enum(name='generationstatus').drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###

