"""updated generation tables

Revision ID: a9331adf66b1
Revises: 2581cbe2d8b0
Create Date: 2025-09-26 18:39:55.514848

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a9331adf66b1'
down_revision = '2581cbe2d8b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation', sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('generation', sa.Column('num_images', sa.Integer(), nullable=False))
    op.add_column('generation', sa.Column('image_size', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('generation', sa.Column('thumbnail', sa.LargeBinary(), nullable=False))
    op.add_column('generation', sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('imagegeneration', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('imagegeneration', sa.Column('widht', sa.Integer(), nullable=False))
    op.add_column('imagegeneration', sa.Column('height', sa.Integer(), nullable=False))
    op.add_column('imagegeneration', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('imagegeneration', 'image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('imagegeneration', 'image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('imagegeneration', 'created_at')
    op.drop_column('imagegeneration', 'height')
    op.drop_column('imagegeneration', 'widht')
    op.drop_column('imagegeneration', 'file_size')
    op.drop_column('generation', 'request_id')
    op.drop_column('generation', 'thumbnail')
    op.drop_column('generation', 'image_size')
    op.drop_column('generation', 'num_images')
    op.drop_column('generation', 'model')
    # ### end Alembic commands ###
