"""thumbnail is nullable

Revision ID: ce4a6a527152
Revises: a9331adf66b1
Create Date: 2025-09-29 20:32:11.355152

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce4a6a527152'
down_revision = 'a9331adf66b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generation', 'thumbnail',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generation', 'thumbnail',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###
