"""added canvases to users

Revision ID: e5acd4312ebb
Revises: ba2365a13394
Create Date: 2025-09-22 22:50:11.783899

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e5acd4312ebb'
down_revision = 'ba2365a13394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
