"""updated column to fix typo

Revision ID: ec643fb13e38
Revises: ce4a6a527152
Create Date: 2025-09-30 02:38:45.420269

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ec643fb13e38'
down_revision = 'ce4a6a527152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imagegeneration', sa.Column('width', sa.Integer(), nullable=False))
    op.drop_column('imagegeneration', 'widht')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imagegeneration', sa.Column('widht', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('imagegeneration', 'width')
    # ### end Alembic commands ###
