"""added status to generation

Revision ID: f443220341eb
Revises: ec643fb13e38
Create Date: 2025-09-30 18:15:25.992114

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f443220341eb'
down_revision = 'ec643fb13e38'
branch_labels = None
depends_on = None

# default owner for now
SYSTEM_USER_ID = "1613fc7a-3379-49ec-9b66-5698ba9ffb18" 


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imagegeneration',         sa.Column(
            'owner_id',
            sa.Uuid(),
            nullable=False,
            server_default=sa.text(f"'{SYSTEM_USER_ID}'")
        ) )
    op.create_foreign_key(None, 'imagegeneration', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'imagegeneration', type_='foreignkey')
    op.drop_column('imagegeneration', 'owner_id')
    # ### end Alembic commands ###




